<?php

/*

|--------------------------------------------------------------------------
| Security Pipeline Cleanup Configuration
|--------------------------------------------------------------------------
|
| This configuration controls the automated cleanup of temporary data
| generated by the ETF Rocket security ingestion and AI processing
| pipeline.
|
| The records stored in these tables are considered transient and may
| be safely removed after processing has completed. Historical security
| data is persisted elsewhere (price history, NAV history, dividend
| history, AUM history, signals, etc.), so these tables are primarily
| used for workflow tracking, debugging, auditing, and failure recovery.
|
| The cleanup command will permanently delete records older than the
| configured retention period.
|
| Tables should generally be listed in dependency order:
|
|     1. Child records
|     2. Parent records
|
| This helps avoid foreign key violations when cascading deletes are
| not configured.
|
| Example:
|
|     php artisan security-pipeline:cleanup
|

*/

return [

    /*
    |--------------------------------------------------------------------------
    | Retention Period
    |--------------------------------------------------------------------------
    |
    | Number of hours to retain pipeline records before they become
    | eligible for deletion.
    |
    | Default: 72 hours (3 days)
    |
    */

    'retention_hours' => 72,

    'tables' => [

        // Security ingestion

        'security_ingestion_batch_items',

        'security_ingestion_batches',

        // AI signals

        'ai_signal_batch_items',

        'ai_signal_batches',

        // AI extractions

        'ai_data_extractions',

        'ai_market_signals',

    ],

];
