<?php

namespace App\Http\Controllers\Dev\ExternalSeeders;

use App\Http\Controllers\Controller;
use App\Models\Security;
use Illuminate\Support\Facades\DB;

class SecuritiesSeederController extends Controller
{
    public function run(): void
    {
        DB::table('securities')
            ->truncate();

        $now = now();

        $securities = [
    [
        'id' => 1,
        'symbol' => 'AAPW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 2,
        'symbol' => 'AAPY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 3,
        'symbol' => 'ABNY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 4,
        'symbol' => 'AIPI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 5,
        'symbol' => 'AIYY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 6,
        'symbol' => 'ALTY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 7,
        'symbol' => 'AMDW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 8,
        'symbol' => 'AMDY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 9,
        'symbol' => 'AMZP',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 10,
        'symbol' => 'AMZW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 11,
        'symbol' => 'AMZY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 12,
        'symbol' => 'APLY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 13,
        'symbol' => 'ARMW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 14,
        'symbol' => 'AVGW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 15,
        'symbol' => 'BABO',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 16,
        'symbol' => 'BABW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 17,
        'symbol' => 'BHDG',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 18,
        'symbol' => 'BIGY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 19,
        'symbol' => 'BLOX',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 20,
        'symbol' => 'BNDI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 21,
        'symbol' => 'BRKC',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 22,
        'symbol' => 'BRKW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 23,
        'symbol' => 'BTCI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 24,
        'symbol' => 'CEPI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 25,
        'symbol' => 'CHPY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 26,
        'symbol' => 'CLIP',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 27,
        'symbol' => 'COII',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 28,
        'symbol' => 'COIW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 29,
        'symbol' => 'CONY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 30,
        'symbol' => 'COSW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 31,
        'symbol' => 'CRCO',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 32,
        'symbol' => 'CRSH',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 33,
        'symbol' => 'CSHI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 34,
        'symbol' => 'CVNY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 35,
        'symbol' => 'CWII',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 36,
        'symbol' => 'DDDD',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 37,
        'symbol' => 'DIPS',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 38,
        'symbol' => 'DISO',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 39,
        'symbol' => 'DIV',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 40,
        'symbol' => 'DJIA',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 41,
        'symbol' => 'DRAY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 42,
        'symbol' => 'EDGQ',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 43,
        'symbol' => 'EDGX',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 44,
        'symbol' => 'EFAS',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 45,
        'symbol' => 'FBY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 46,
        'symbol' => 'FEAT',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 47,
        'symbol' => 'FEPI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 48,
        'symbol' => 'FIAT',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 49,
        'symbol' => 'FIAX',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 50,
        'symbol' => 'FIVY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 51,
        'symbol' => 'GDXW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 52,
        'symbol' => 'GDXY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 53,
        'symbol' => 'GIAX',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 54,
        'symbol' => 'GIF',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 55,
        'symbol' => 'GLDN',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 56,
        'symbol' => 'GLDW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 57,
        'symbol' => 'GLDY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 58,
        'symbol' => 'GMEY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 59,
        'symbol' => 'GOOP',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 60,
        'symbol' => 'GOOW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 61,
        'symbol' => 'GOOY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 62,
        'symbol' => 'GPTY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 63,
        'symbol' => 'HIYY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 64,
        'symbol' => 'HOII',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 65,
        'symbol' => 'HOOW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 66,
        'symbol' => 'HOOY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 67,
        'symbol' => 'HYBI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 68,
        'symbol' => 'IAUI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 69,
        'symbol' => 'IWMI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 70,
        'symbol' => 'IWMY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 71,
        'symbol' => 'IYRI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 72,
        'symbol' => 'JEPI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 73,
        'symbol' => 'JPMO',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 74,
        'symbol' => 'JPO',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 75,
        'symbol' => 'KCOP',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 76,
        'symbol' => 'KGLD',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 77,
        'symbol' => 'KQQQ',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 78,
        'symbol' => 'KSLV',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 79,
        'symbol' => 'KYLD',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 80,
        'symbol' => 'LFGY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 81,
        'symbol' => 'LLII',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 82,
        'symbol' => 'LQID',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 83,
        'symbol' => 'MARO',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 84,
        'symbol' => 'METW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 85,
        'symbol' => 'MINY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 86,
        'symbol' => 'MLPI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 87,
        'symbol' => 'MRNY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 88,
        'symbol' => 'MSFO',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 89,
        'symbol' => 'MSFW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 90,
        'symbol' => 'MSFY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 91,
        'symbol' => 'MSII',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 92,
        'symbol' => 'MSST',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 93,
        'symbol' => 'MST',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 94,
        'symbol' => 'MSTW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 95,
        'symbol' => 'MSTY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 96,
        'symbol' => 'NEHI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 97,
        'symbol' => 'NFLP',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 98,
        'symbol' => 'NFLW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 99,
        'symbol' => 'NFLY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 100,
        'symbol' => 'NGHT',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 101,
        'symbol' => 'NIHI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 102,
        'symbol' => 'NLSI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 103,
        'symbol' => 'NUKX',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 104,
        'symbol' => 'NVDW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 105,
        'symbol' => 'NVDY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 106,
        'symbol' => 'NVII',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 107,
        'symbol' => 'NVIT',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 108,
        'symbol' => 'OARK',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 109,
        'symbol' => 'PLTI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 110,
        'symbol' => 'PLTW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 111,
        'symbol' => 'PLTY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 112,
        'symbol' => 'PYPY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 113,
        'symbol' => 'QCLR',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 114,
        'symbol' => 'QDIV',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 115,
        'symbol' => 'QDTE',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 116,
        'symbol' => 'QDTY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 117,
        'symbol' => 'QLDY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 118,
        'symbol' => 'QQQH',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 119,
        'symbol' => 'QQQI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 120,
        'symbol' => 'QQQT',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 121,
        'symbol' => 'QQQY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 122,
        'symbol' => 'QYLD',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 123,
        'symbol' => 'QYLG',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 124,
        'symbol' => 'RBLY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 125,
        'symbol' => 'RDTE',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 126,
        'symbol' => 'RDTY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 127,
        'symbol' => 'RDYY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 128,
        'symbol' => 'RNTY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 129,
        'symbol' => 'RYLD',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 130,
        'symbol' => 'RYLG',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 131,
        'symbol' => 'SDEM',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 132,
        'symbol' => 'SDIV',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 133,
        'symbol' => 'SDTY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 134,
        'symbol' => 'SLVX',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 135,
        'symbol' => 'SMCY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 136,
        'symbol' => 'SNOY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 137,
        'symbol' => 'SOXY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 138,
        'symbol' => 'SPYH',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 139,
        'symbol' => 'SPYI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 140,
        'symbol' => 'SPYT',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 141,
        'symbol' => 'SRET',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 142,
        'symbol' => 'TDAQ',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 143,
        'symbol' => 'TDAX',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 144,
        'symbol' => 'TEST',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 145,
        'symbol' => 'TLTI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 146,
        'symbol' => 'TOPW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 147,
        'symbol' => 'TPAY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 148,
        'symbol' => 'TSII',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 149,
        'symbol' => 'TSLP',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 150,
        'symbol' => 'TSLW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 151,
        'symbol' => 'TSLY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 152,
        'symbol' => 'TSMY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 153,
        'symbol' => 'TSPY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 154,
        'symbol' => 'TSYW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 155,
        'symbol' => 'TSYX',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 156,
        'symbol' => 'UBEW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 157,
        'symbol' => 'ULTI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 158,
        'symbol' => 'ULTY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 159,
        'symbol' => 'UNHW',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 160,
        'symbol' => 'USOY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 161,
        'symbol' => 'WDTE',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 162,
        'symbol' => 'WEEK',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 163,
        'symbol' => 'WEPN',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 164,
        'symbol' => 'WMTI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 165,
        'symbol' => 'WNTR',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 166,
        'symbol' => 'XBCI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 167,
        'symbol' => 'XCLR',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 168,
        'symbol' => 'XDTE',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 169,
        'symbol' => 'XOMO',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 170,
        'symbol' => 'XPAY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 171,
        'symbol' => 'XQQI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 172,
        'symbol' => 'XSPI',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 173,
        'symbol' => 'XYLD',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 174,
        'symbol' => 'XYLG',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 175,
        'symbol' => 'XYZY',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 176,
        'symbol' => 'YBIT',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 177,
        'symbol' => 'YBMN',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 178,
        'symbol' => 'YBTC',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 179,
        'symbol' => 'YETH',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 180,
        'symbol' => 'YMAG',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 181,
        'symbol' => 'YMAX',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
    [
        'id' => 182,
        'symbol' => 'YQQQ',
        'security_type_id' => 1,
        'status_id' => 4,
    ],
];

        $securities = array_map(

            function ($security) use ($now) {

                $security['created_at'] =
                    $now;

                $security['updated_at'] =
                    $now;

                return $security;
            },

            $securities

        );

        Security::insert(
            $securities
        );
    }
}