<?php

namespace App\Http\Controllers\Dev\ExternalSeeders;

use App\Http\Controllers\Controller;
use App\Models\SecurityDetail;
use Illuminate\Support\Facades\DB;

class SecurityDetailsSeederController extends Controller
{
    public function run(): void
    {
        DB::table('security_details')
            ->truncate();

        $now = now();

        $details = [
            [
                'security_id' => 1,
                'run_day' => 1,
                'run_hour' => 0,
                'security_name' => 'Roundhill AAPL WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/aapw/',
                'notes' => null,
            ],
            [
                'security_id' => 2,
                'run_day' => 2,
                'run_hour' => 1,
                'security_name' => 'Kurv Apple Covered Call ETF',
                'etf_issuer_id' => 10,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.kurvinvest.com/etf/aapy',
                'notes' => null,
            ],
            [
                'security_id' => 3,
                'run_day' => 3,
                'run_hour' => 2,
                'security_name' => 'YieldMax ABNB Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/abny/',
                'notes' => null,
            ],
            [
                'security_id' => 4,
                'run_day' => 4,
                'run_hour' => 3,
                'security_name' => 'REX AI Equity Premium Income ETF',
                'etf_issuer_id' => 3,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.65,
                'website_url' => 'https://www.rexshares.com/aipi/',
                'notes' => 'AI-focused income ETF',
            ],
            [
                'security_id' => 5,
                'run_day' => 5,
                'run_hour' => 4,
                'security_name' => 'YieldMax AI Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/aiyy/',
                'notes' => null,
            ],
            [
                'security_id' => 6,
                'run_day' => 6,
                'run_hour' => 5,
                'security_name' => 'Global X Alternative Income ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 16,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 1.14,
                'website_url' => 'https://www.globalxetfs.com/funds/alty/',
                'notes' => 'Alternative income strategy ETF',
            ],
            [
                'security_id' => 7,
                'run_day' => 7,
                'run_hour' => 6,
                'security_name' => 'Roundhill AMD WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/amdw/',
                'notes' => null,
            ],
            [
                'security_id' => 8,
                'run_day' => 1,
                'run_hour' => 7,
                'security_name' => 'YieldMax AMD Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 2,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.23,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/amdy/',
                'notes' => null,
            ],
            [
                'security_id' => 9,
                'run_day' => 2,
                'run_hour' => 8,
                'security_name' => 'Kurv Amazon Covered Call ETF',
                'etf_issuer_id' => 10,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.kurvinvest.com/etf/amzp',
                'notes' => null,
            ],
            [
                'security_id' => 10,
                'run_day' => 3,
                'run_hour' => 9,
                'security_name' => 'Roundhill AMZN WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/amzw/',
                'notes' => null,
            ],
            [
                'security_id' => 11,
                'run_day' => 4,
                'run_hour' => 10,
                'security_name' => 'YieldMax AMZN Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.45,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/amzy/',
                'notes' => null,
            ],
            [
                'security_id' => 12,
                'run_day' => 5,
                'run_hour' => 11,
                'security_name' => 'YieldMax AAPL Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.14,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/aply/',
                'notes' => null,
            ],
            [
                'security_id' => 13,
                'run_day' => 6,
                'run_hour' => 12,
                'security_name' => 'Roundhill ARM WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/armw/',
                'notes' => null,
            ],
            [
                'security_id' => 14,
                'run_day' => 7,
                'run_hour' => 13,
                'security_name' => 'Roundhill AVGO WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/avgw/',
                'notes' => null,
            ],
            [
                'security_id' => 15,
                'run_day' => 1,
                'run_hour' => 14,
                'security_name' => 'YieldMax BABA Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.14,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/babo/',
                'notes' => null,
            ],
            [
                'security_id' => 16,
                'run_day' => 2,
                'run_hour' => 15,
                'security_name' => 'Roundhill BABA WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/babw/',
                'notes' => null,
            ],
            [
                'security_id' => 17,
                'run_day' => 3,
                'run_hour' => 16,
                'security_name' => 'Nicholas Black Swan Hedged Equity ETF',
                'etf_issuer_id' => 11,
                'etf_strategy_type_id' => 19,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.95,
                'website_url' => 'https://nicholasx.com/bhdg/',
                'notes' => 'Tail-risk hedged ETF',
            ],
            [
                'security_id' => 18,
                'run_day' => 4,
                'run_hour' => 17,
                'security_name' => 'YieldMax Big Tech Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/bigy/',
                'notes' => 'YieldMax Lite ETF',
            ],
            [
                'security_id' => 19,
                'run_day' => 5,
                'run_hour' => 18,
                'security_name' => 'Nicholas Crypto Income ETF',
                'etf_issuer_id' => 11,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://nicholasx.com/blox/',
                'notes' => null,
            ],
            [
                'security_id' => 20,
                'run_day' => 6,
                'run_hour' => 19,
                'security_name' => 'NEOS Enhanced Income Aggregate Bond ETF',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 23,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.58,
                'website_url' => 'https://neosfunds.com/bndi/',
                'notes' => 'Bond income ETF',
            ],
            [
                'security_id' => 21,
                'run_day' => 7,
                'run_hour' => 20,
                'security_name' => 'YieldMax BRK.B Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.14,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/brkc/',
                'notes' => null,
            ],
            [
                'security_id' => 22,
                'run_day' => 1,
                'run_hour' => 21,
                'security_name' => 'Roundhill BRK.B WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/brkw/',
                'notes' => null,
            ],
            [
                'security_id' => 23,
                'run_day' => 2,
                'run_hour' => 22,
                'security_name' => 'NEOS Bitcoin High Income ETF',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.98,
                'website_url' => 'https://neosfunds.com/btci/',
                'notes' => 'Bitcoin income ETF',
            ],
            [
                'security_id' => 24,
                'run_day' => 3,
                'run_hour' => 23,
                'security_name' => 'REX Crypto Equity Premium Income ETF',
                'etf_issuer_id' => 3,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.85,
                'website_url' => 'https://www.rexshares.com/cepi/',
                'notes' => 'Crypto-focused income ETF',
            ],
            [
                'security_id' => 25,
                'run_day' => 4,
                'run_hour' => 0,
                'security_name' => 'YieldMax Semiconductor Portfolio Option Income ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.03,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/chpy/',
                'notes' => null,
            ],
            [
                'security_id' => 26,
                'run_day' => 5,
                'run_hour' => 1,
                'security_name' => 'Global X 1-3 Month T-Bill ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 9,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.07,
                'website_url' => 'https://www.globalxetfs.com/funds/clip/',
                'notes' => 'Treasury bill ETF',
            ],
            [
                'security_id' => 27,
                'run_day' => 6,
                'run_hour' => 2,
                'security_name' => 'REX COIN Weekly Income ETF',
                'etf_issuer_id' => 3,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.rexshares.com/coii/',
                'notes' => null,
            ],
            [
                'security_id' => 28,
                'run_day' => 7,
                'run_hour' => 3,
                'security_name' => 'Roundhill COIN WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/coiw/',
                'notes' => null,
            ],
            [
                'security_id' => 29,
                'run_day' => 1,
                'run_hour' => 4,
                'security_name' => 'YieldMax COIN Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/cony/',
                'notes' => null,
            ],
            [
                'security_id' => 30,
                'run_day' => 2,
                'run_hour' => 5,
                'security_name' => 'Roundhill COST WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/cosw/',
                'notes' => null,
            ],
            [
                'security_id' => 31,
                'run_day' => 3,
                'run_hour' => 6,
                'security_name' => 'YieldMax CRCL Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.14,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/crco/',
                'notes' => null,
            ],
            [
                'security_id' => 32,
                'run_day' => 4,
                'run_hour' => 7,
                'security_name' => 'YieldMax Short TSLA Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.14,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/crsh/',
                'notes' => 'Short strategy ETF',
            ],
            [
                'security_id' => 33,
                'run_day' => 5,
                'run_hour' => 8,
                'security_name' => 'NEOS Enhanced Income Cash Alternative ETF',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 21,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.38,
                'website_url' => 'https://neosfunds.com/cshi/',
                'notes' => 'Cash alternative ETF',
            ],
            [
                'security_id' => 34,
                'run_day' => 6,
                'run_hour' => 9,
                'security_name' => 'YieldMax CVNA Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.14,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/cvny/',
                'notes' => null,
            ],
            [
                'security_id' => 35,
                'run_day' => 7,
                'run_hour' => 10,
                'security_name' => 'REX CRWD Weekly Income ETF',
                'etf_issuer_id' => 3,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.rexshares.com/cwii/',
                'notes' => null,
            ],
            [
                'security_id' => 36,
                'run_day' => 1,
                'run_hour' => 11,
                'security_name' => 'YieldMax TSLA TSLL Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/dddd/',
                'notes' => null,
            ],
            [
                'security_id' => 37,
                'run_day' => 2,
                'run_hour' => 12,
                'security_name' => 'YieldMax Short NVDA Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.14,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/dips/',
                'notes' => 'Short strategy ETF',
            ],
            [
                'security_id' => 38,
                'run_day' => 3,
                'run_hour' => 13,
                'security_name' => 'YieldMax DIS Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.14,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/diso/',
                'notes' => null,
            ],
            [
                'security_id' => 39,
                'run_day' => 4,
                'run_hour' => 14,
                'security_name' => 'Global X SuperDividend U.S. ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 10,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.45,
                'website_url' => 'https://www.globalxetfs.com/funds/div/',
                'notes' => 'U.S. high dividend ETF',
            ],
            [
                'security_id' => 40,
                'run_day' => 5,
                'run_hour' => 15,
                'security_name' => 'Global X Dow 30 Covered Call ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.45,
                'website_url' => 'https://www.globalxetfs.com/funds/djia/',
                'notes' => null,
            ],
            [
                'security_id' => 41,
                'run_day' => 6,
                'run_hour' => 16,
                'security_name' => 'YieldMax DKNG Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.14,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/dray/',
                'notes' => null,
            ],
            [
                'security_id' => 42,
                'run_day' => 7,
                'run_hour' => 17,
                'security_name' => 'Global X S&P 500 Quality Dividend Covered Call ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.60,
                'website_url' => 'https://www.globalxetfs.com/funds/edgq/',
                'notes' => null,
            ],
            [
                'security_id' => 43,
                'run_day' => 1,
                'run_hour' => 18,
                'security_name' => 'Global X S&P 500 Covered Call & Growth ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.60,
                'website_url' => 'https://www.globalxetfs.com/funds/edgx/',
                'notes' => null,
            ],
            [
                'security_id' => 44,
                'run_day' => 2,
                'run_hour' => 19,
                'security_name' => 'Global X MSCI SuperDividend EAFE ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 10,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.56,
                'website_url' => 'https://www.globalxetfs.com/funds/efas/',
                'notes' => 'International dividend ETF',
            ],
            [
                'security_id' => 45,
                'run_day' => 3,
                'run_hour' => 20,
                'security_name' => 'YieldMax META Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/fby/',
                'notes' => null,
            ],
            [
                'security_id' => 46,
                'run_day' => 4,
                'run_hour' => 21,
                'security_name' => 'YieldMax Dorsey Wright Featured 5 Income ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/feat/',
                'notes' => 'Portfolio strategy ETF',
            ],
            [
                'security_id' => 47,
                'run_day' => 5,
                'run_hour' => 22,
                'security_name' => 'REX FANG & Innovation Equity Premium Income ETF',
                'etf_issuer_id' => 3,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.65,
                'website_url' => 'https://www.rexshares.com/fepi/',
                'notes' => null,
            ],
            [
                'security_id' => 48,
                'run_day' => 6,
                'run_hour' => 23,
                'security_name' => 'YieldMax Short COIN Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.14,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/fiat/',
                'notes' => 'Short strategy ETF',
            ],
            [
                'security_id' => 49,
                'run_day' => 7,
                'run_hour' => 0,
                'security_name' => 'Nicholas Fixed Income Alternative ETF',
                'etf_issuer_id' => 11,
                'etf_strategy_type_id' => 16,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.95,
                'website_url' => 'https://nicholasx.com/fiax/',
                'notes' => 'Fixed income alternative ETF',
            ],
            [
                'security_id' => 50,
                'run_day' => 1,
                'run_hour' => 1,
                'security_name' => 'YieldMax Dorsey Wright Hybrid 5 Income ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/fivy/',
                'notes' => 'Portfolio strategy ETF',
            ],
            [
                'security_id' => 51,
                'run_day' => 2,
                'run_hour' => 2,
                'security_name' => 'Roundhill Gold Miners WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/gdxw/',
                'notes' => null,
            ],
            [
                'security_id' => 52,
                'run_day' => 3,
                'run_hour' => 3,
                'security_name' => 'YieldMax Gold Miners Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/gdxy/',
                'notes' => null,
            ],
            [
                'security_id' => 53,
                'run_day' => 4,
                'run_hour' => 4,
                'security_name' => 'Nicholas Global Income Alternative ETF',
                'etf_issuer_id' => 11,
                'etf_strategy_type_id' => 16,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.95,
                'website_url' => 'https://nicholasx.com/giax/',
                'notes' => 'Global alternative income ETF',
            ],
            [
                'security_id' => 54,
                'run_day' => 5,
                'run_hour' => 5,
                'security_name' => 'REX Golden Income ETF',
                'etf_issuer_id' => 3,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.75,
                'website_url' => 'https://www.rexshares.com/gif/',
                'notes' => 'Multi-asset income ETF',
            ],
            [
                'security_id' => 55,
                'run_day' => 6,
                'run_hour' => 6,
                'security_name' => 'Nicholas Gold Income ETF',
                'etf_issuer_id' => 11,
                'etf_strategy_type_id' => 25,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.95,
                'website_url' => 'https://nicholasx.com/gldn/',
                'notes' => 'Gold income ETF',
            ],
            [
                'security_id' => 56,
                'run_day' => 7,
                'run_hour' => 7,
                'security_name' => 'Roundhill Gold WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/gldw/',
                'notes' => null,
            ],
            [
                'security_id' => 57,
                'run_day' => 1,
                'run_hour' => 8,
                'security_name' => 'Defiance Gold Enhanced Option Income ETF',
                'etf_issuer_id' => 6,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 1.19,
                'website_url' => 'https://www.defianceetfs.com/gldy/',
                'notes' => 'Gold income ETF',
            ],
            [
                'security_id' => 58,
                'run_day' => 2,
                'run_hour' => 9,
                'security_name' => 'YieldMax GME Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.14,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/gmey/',
                'notes' => null,
            ],
            [
                'security_id' => 59,
                'run_day' => 3,
                'run_hour' => 10,
                'security_name' => 'Kurv Alphabet Covered Call ETF',
                'etf_issuer_id' => 10,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.kurvinvest.com/etf/goop',
                'notes' => null,
            ],
            [
                'security_id' => 60,
                'run_day' => 4,
                'run_hour' => 11,
                'security_name' => 'Roundhill GOOGL WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/goow/',
                'notes' => null,
            ],
            [
                'security_id' => 61,
                'run_day' => 5,
                'run_hour' => 12,
                'security_name' => 'YieldMax GOOGL Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 2,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/gooy/',
                'notes' => null,
            ],
            [
                'security_id' => 62,
                'run_day' => 6,
                'run_hour' => 13,
                'security_name' => 'YieldMax PLTR Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/gpty/',
                'notes' => null,
            ],
            [
                'security_id' => 63,
                'run_day' => 7,
                'run_hour' => 14,
                'security_name' => 'YieldMax HIMS Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.14,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/hiyy/',
                'notes' => null,
            ],
            [
                'security_id' => 64,
                'run_day' => 1,
                'run_hour' => 15,
                'security_name' => 'REX HOOD Weekly Income ETF',
                'etf_issuer_id' => 3,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.rexshares.com/hoii/',
                'notes' => null,
            ],
            [
                'security_id' => 65,
                'run_day' => 2,
                'run_hour' => 16,
                'security_name' => 'Roundhill HOOD WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/hoow/',
                'notes' => null,
            ],
            [
                'security_id' => 66,
                'run_day' => 3,
                'run_hour' => 17,
                'security_name' => 'YieldMax HOOD Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.14,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/hooy/',
                'notes' => null,
            ],
            [
                'security_id' => 67,
                'run_day' => 4,
                'run_hour' => 18,
                'security_name' => 'NEOS Enhanced Income High Yield Bond ETF',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 20,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.68,
                'website_url' => 'https://neosfunds.com/hybi/',
                'notes' => 'High yield bond ETF',
            ],
            [
                'security_id' => 68,
                'run_day' => 5,
                'run_hour' => 19,
                'security_name' => 'NEOS Gold Income ETF',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.68,
                'website_url' => 'https://neosfunds.com/iaui/',
                'notes' => 'Gold income ETF',
            ],
            [
                'security_id' => 69,
                'run_day' => 6,
                'run_hour' => 20,
                'security_name' => 'NEOS Russell 2000 High Income ETF',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.68,
                'website_url' => 'https://neosfunds.com/iwmi/',
                'notes' => null,
            ],
            [
                'security_id' => 70,
                'run_day' => 7,
                'run_hour' => 21,
                'security_name' => 'Defiance Russell 2000 Enhanced Option Income ETF',
                'etf_issuer_id' => 6,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.defianceetfs.com/iwmy/',
                'notes' => '0DTE enhanced income ETF',
            ],
            [
                'security_id' => 71,
                'run_day' => 1,
                'run_hour' => 22,
                'security_name' => 'NEOS Real Estate High Income ETF',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.68,
                'website_url' => 'https://neosfunds.com/iyri/',
                'notes' => 'Real estate income ETF',
            ],
            [
                'security_id' => 72,
                'run_day' => 2,
                'run_hour' => 23,
                'security_name' => 'JPMorgan Equity Premium Income ETF',
                'etf_issuer_id' => 4,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.35,
                'website_url' => 'https://am.jpmorgan.com/us/en/asset-management/adv/products/jpmorgan-equity-premium-income-etf-etf-shares-46641q3323',
                'notes' => null,
            ],
            [
                'security_id' => 73,
                'run_day' => 3,
                'run_hour' => 0,
                'security_name' => 'YieldMax JPM Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.14,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/jpmo/',
                'notes' => null,
            ],
            [
                'security_id' => 74,
                'run_day' => 4,
                'run_hour' => 1,
                'security_name' => 'YieldMax JPM Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/jpo/',
                'notes' => null,
            ],
            [
                'security_id' => 75,
                'run_day' => 5,
                'run_hour' => 2,
                'security_name' => 'Kurv Copper Covered Call ETF',
                'etf_issuer_id' => 10,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.89,
                'website_url' => 'https://www.kurvinvest.com/etf/kcop',
                'notes' => 'Copper strategy ETF',
            ],
            [
                'security_id' => 76,
                'run_day' => 6,
                'run_hour' => 3,
                'security_name' => 'Kurv Gold Covered Call ETF',
                'etf_issuer_id' => 10,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.89,
                'website_url' => 'https://www.kurvinvest.com/etf/kgld',
                'notes' => 'Gold strategy ETF',
            ],
            [
                'security_id' => 77,
                'run_day' => 7,
                'run_hour' => 4,
                'security_name' => 'Kurv Nasdaq-100 Covered Call ETF',
                'etf_issuer_id' => 10,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.kurvinvest.com/etf/kqqq',
                'notes' => null,
            ],
            [
                'security_id' => 78,
                'run_day' => 1,
                'run_hour' => 5,
                'security_name' => 'Kurv Silver Covered Call ETF',
                'etf_issuer_id' => 10,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.89,
                'website_url' => 'https://www.kurvinvest.com/etf/kslv',
                'notes' => 'Silver strategy ETF',
            ],
            [
                'security_id' => 79,
                'run_day' => 2,
                'run_hour' => 6,
                'security_name' => 'Kurv Yield Premium Strategy ETF',
                'etf_issuer_id' => 10,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.kurvinvest.com/etf/kyld',
                'notes' => null,
            ],
            [
                'security_id' => 80,
                'run_day' => 3,
                'run_hour' => 7,
                'security_name' => 'YieldMax Crypto Industry & Tech Portfolio Option Income ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.02,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/lfgy/',
                'notes' => null,
            ],
            [
                'security_id' => 81,
                'run_day' => 4,
                'run_hour' => 8,
                'security_name' => 'REX LLY Weekly Income ETF',
                'etf_issuer_id' => 3,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.rexshares.com/llii/',
                'notes' => null,
            ],
            [
                'security_id' => 82,
                'run_day' => 5,
                'run_hour' => 9,
                'security_name' => 'Kurv Liquidity Premium Strategy ETF',
                'etf_issuer_id' => 10,
                'etf_strategy_type_id' => 21,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.45,
                'website_url' => 'https://www.kurvinvest.com/etf/lqid',
                'notes' => 'Cash alternative ETF',
            ],
            [
                'security_id' => 83,
                'run_day' => 6,
                'run_hour' => 10,
                'security_name' => 'YieldMax MARA Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/maro/',
                'notes' => null,
            ],
            [
                'security_id' => 84,
                'run_day' => 7,
                'run_hour' => 11,
                'security_name' => 'Roundhill META WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/metw/',
                'notes' => null,
            ],
            [
                'security_id' => 85,
                'run_day' => 1,
                'run_hour' => 12,
                'security_name' => 'YieldMax MRNA Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/miny/',
                'notes' => null,
            ],
            [
                'security_id' => 86,
                'run_day' => 2,
                'run_hour' => 13,
                'security_name' => 'NEOS MLP & Energy Infrastructure Income ETF',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 22,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.85,
                'website_url' => 'https://neosfunds.com/mlpi/',
                'notes' => 'MLP income ETF',
            ],
            [
                'security_id' => 87,
                'run_day' => 3,
                'run_hour' => 14,
                'security_name' => 'YieldMax MRNA Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/mrny/',
                'notes' => null,
            ],
            [
                'security_id' => 88,
                'run_day' => 4,
                'run_hour' => 15,
                'security_name' => 'YieldMax MSFT Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/msfo/',
                'notes' => null,
            ],
            [
                'security_id' => 89,
                'run_day' => 5,
                'run_hour' => 16,
                'security_name' => 'Roundhill MSFT WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/msfw/',
                'notes' => null,
            ],
            [
                'security_id' => 90,
                'run_day' => 6,
                'run_hour' => 17,
                'security_name' => 'Kurv Microsoft Covered Call ETF',
                'etf_issuer_id' => 10,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.kurvinvest.com/etf/msfy',
                'notes' => null,
            ],
            [
                'security_id' => 91,
                'run_day' => 7,
                'run_hour' => 18,
                'security_name' => 'REX MSTR Weekly Income ETF',
                'etf_issuer_id' => 3,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.rexshares.com/msii/',
                'notes' => null,
            ],
            [
                'security_id' => 92,
                'run_day' => 1,
                'run_hour' => 19,
                'security_name' => 'YieldMax MSTR Performance & Distribution Target 25 ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/msst/',
                'notes' => 'YieldMax Lite ETF',
            ],
            [
                'security_id' => 93,
                'run_day' => 2,
                'run_hour' => 20,
                'security_name' => 'Defiance Daily Target 2X Long MSTR ETF',
                'etf_issuer_id' => 6,
                'etf_strategy_type_id' => 18,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 1.29,
                'website_url' => 'https://www.defianceetfs.com/mst/',
                'notes' => 'Leveraged ETF',
            ],
            [
                'security_id' => 94,
                'run_day' => 3,
                'run_hour' => 21,
                'security_name' => 'Roundhill MSTR WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/mstw/',
                'notes' => null,
            ],
            [
                'security_id' => 95,
                'run_day' => 4,
                'run_hour' => 22,
                'security_name' => 'YieldMax MSTR Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/msty/',
                'notes' => null,
            ],
            [
                'security_id' => 96,
                'run_day' => 5,
                'run_hour' => 23,
                'security_name' => 'NEOS Enhanced Income ETF',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.68,
                'website_url' => 'https://neosfunds.com/nehi/',
                'notes' => 'Enhanced income strategy ETF',
            ],
            [
                'security_id' => 97,
                'run_day' => 6,
                'run_hour' => 0,
                'security_name' => 'Kurv Netflix Covered Call ETF',
                'etf_issuer_id' => 10,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.kurvinvest.com/etf/nflp',
                'notes' => null,
            ],
            [
                'security_id' => 98,
                'run_day' => 7,
                'run_hour' => 1,
                'security_name' => 'Roundhill NFLX WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/nflw/',
                'notes' => null,
            ],
            [
                'security_id' => 99,
                'run_day' => 1,
                'run_hour' => 2,
                'security_name' => 'YieldMax NFLX Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/nfly/',
                'notes' => null,
            ],
            [
                'security_id' => 100,
                'run_day' => 2,
                'run_hour' => 3,
                'security_name' => 'Nicholas Overnight Risk Managed ETF',
                'etf_issuer_id' => 11,
                'etf_strategy_type_id' => 27,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.89,
                'website_url' => 'https://nicholasx.com/nght/',
                'notes' => 'Risk-managed strategy ETF',
            ],
            [
                'security_id' => 101,
                'run_day' => 3,
                'run_hour' => 4,
                'security_name' => 'NEOS Nasdaq 100 High Income ETF',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.68,
                'website_url' => 'https://neosfunds.com/nihi/',
                'notes' => 'Enhanced income ETF',
            ],
            [
                'security_id' => 102,
                'run_day' => 4,
                'run_hour' => 5,
                'security_name' => 'NEOS Enhanced Income 1-3 Month T-Bill ETF',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 9,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.38,
                'website_url' => 'https://neosfunds.com/nlsi/',
                'notes' => 'Treasury income ETF',
            ],
            [
                'security_id' => 103,
                'run_day' => 5,
                'run_hour' => 6,
                'security_name' => 'Nicholas Uranium & Nuclear Energy Income ETF',
                'etf_issuer_id' => 11,
                'etf_strategy_type_id' => 22,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 1.05,
                'website_url' => 'https://nicholasx.com/nukx/',
                'notes' => 'Nuclear energy ETF',
            ],
            [
                'security_id' => 104,
                'run_day' => 6,
                'run_hour' => 7,
                'security_name' => 'Roundhill NVDA WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/nvdw/',
                'notes' => null,
            ],
            [
                'security_id' => 105,
                'run_day' => 7,
                'run_hour' => 8,
                'security_name' => 'YieldMax NVDA Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/nvdy/',
                'notes' => null,
            ],
            [
                'security_id' => 106,
                'run_day' => 1,
                'run_hour' => 9,
                'security_name' => 'REX NVDA Growth & Income ETF',
                'etf_issuer_id' => 3,
                'etf_strategy_type_id' => 3,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.rexshares.com/nvii/',
                'notes' => null,
            ],
            [
                'security_id' => 107,
                'run_day' => 2,
                'run_hour' => 10,
                'security_name' => 'YieldMax NVDA Performance & Distribution Target 25 ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/nvit/',
                'notes' => 'YieldMax Lite ETF',
            ],
            [
                'security_id' => 108,
                'run_day' => 3,
                'run_hour' => 11,
                'security_name' => 'YieldMax Innovation Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.29,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/oark/',
                'notes' => 'ARKK-focused strategy ETF',
            ],
            [
                'security_id' => 109,
                'run_day' => 4,
                'run_hour' => 12,
                'security_name' => 'REX PLTR Weekly Income ETF',
                'etf_issuer_id' => 3,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.rexshares.com/plti/',
                'notes' => null,
            ],
            [
                'security_id' => 110,
                'run_day' => 5,
                'run_hour' => 13,
                'security_name' => 'Roundhill PLTR WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/pltw/',
                'notes' => null,
            ],
            [
                'security_id' => 111,
                'run_day' => 6,
                'run_hour' => 14,
                'security_name' => 'YieldMax PLTR Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/plty/',
                'notes' => null,
            ],
            [
                'security_id' => 112,
                'run_day' => 7,
                'run_hour' => 15,
                'security_name' => 'YieldMax PYPL Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/pypy/',
                'notes' => null,
            ],
            [
                'security_id' => 113,
                'run_day' => 1,
                'run_hour' => 16,
                'security_name' => 'Global X Nasdaq 100 Collar 95-110 ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 17,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.60,
                'website_url' => 'https://www.globalxetfs.com/funds/qclr/',
                'notes' => 'Collar strategy ETF',
            ],
            [
                'security_id' => 114,
                'run_day' => 2,
                'run_hour' => 17,
                'security_name' => 'Global X S&P 500 Quality Dividend ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 10,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.20,
                'website_url' => 'https://www.globalxetfs.com/funds/qdiv/',
                'notes' => 'Quality dividend ETF',
            ],
            [
                'security_id' => 115,
                'run_day' => 3,
                'run_hour' => 18,
                'security_name' => 'Roundhill Innovation-100 0DTE Covered Call Strategy ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.95,
                'website_url' => 'https://www.roundhillinvestments.com/etf/qdte/',
                'notes' => '0DTE strategy ETF',
            ],
            [
                'security_id' => 116,
                'run_day' => 4,
                'run_hour' => 19,
                'security_name' => 'YieldMax Nasdaq 100 0DTE Covered Call Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/qdty/',
                'notes' => '0DTE strategy ETF',
            ],
            [
                'security_id' => 117,
                'run_day' => 5,
                'run_hour' => 20,
                'security_name' => 'Defiance Nasdaq 100 Covered Call ETF',
                'etf_issuer_id' => 6,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.88,
                'website_url' => 'https://www.defianceetfs.com/qldy/',
                'notes' => null,
            ],
            [
                'security_id' => 118,
                'run_day' => 6,
                'run_hour' => 21,
                'security_name' => 'NEOS Nasdaq 100 Hedged Equity Income ETF',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 19,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.58,
                'website_url' => 'https://neosfunds.com/qqqh/',
                'notes' => 'Hedged equity ETF',
            ],
            [
                'security_id' => 119,
                'run_day' => 7,
                'run_hour' => 22,
                'security_name' => 'NEOS Nasdaq-100 High Income ETF',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.68,
                'website_url' => 'https://neosfunds.com/qqqi/',
                'notes' => null,
            ],
            [
                'security_id' => 120,
                'run_day' => 1,
                'run_hour' => 23,
                'security_name' => 'Defiance Nasdaq 100 Target Income ETF',
                'etf_issuer_id' => 6,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.94,
                'website_url' => 'https://www.defianceetfs.com/qqqt/',
                'notes' => 'Target income ETF',
            ],
            [
                'security_id' => 121,
                'run_day' => 2,
                'run_hour' => 0,
                'security_name' => 'Defiance Nasdaq 100 Enhanced Option Income ETF',
                'etf_issuer_id' => 6,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.defianceetfs.com/qqqy/',
                'notes' => '0DTE enhanced income ETF',
            ],
            [
                'security_id' => 122,
                'run_day' => 3,
                'run_hour' => 1,
                'security_name' => 'Global X Nasdaq 100 Covered Call ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.60,
                'website_url' => 'https://www.globalxetfs.com/funds/qyld/',
                'notes' => null,
            ],
            [
                'security_id' => 123,
                'run_day' => 4,
                'run_hour' => 2,
                'security_name' => 'Global X Nasdaq 100 Covered Call & Growth ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.60,
                'website_url' => 'https://www.globalxetfs.com/funds/qylg/',
                'notes' => null,
            ],
            [
                'security_id' => 124,
                'run_day' => 5,
                'run_hour' => 3,
                'security_name' => 'YieldMax RBLX Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/rbly/',
                'notes' => null,
            ],
            [
                'security_id' => 125,
                'run_day' => 6,
                'run_hour' => 4,
                'security_name' => 'Roundhill Russell 2000 0DTE Covered Call Strategy ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.95,
                'website_url' => 'https://www.roundhillinvestments.com/etf/rdte/',
                'notes' => '0DTE strategy ETF',
            ],
            [
                'security_id' => 126,
                'run_day' => 7,
                'run_hour' => 5,
                'security_name' => 'YieldMax Russell 2000 0DTE Covered Call Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/rdty/',
                'notes' => '0DTE strategy ETF',
            ],
            [
                'security_id' => 127,
                'run_day' => 1,
                'run_hour' => 6,
                'security_name' => 'YieldMax RDDT Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.14,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/rdyy/',
                'notes' => null,
            ],
            [
                'security_id' => 128,
                'run_day' => 2,
                'run_hour' => 7,
                'security_name' => 'YieldMax Target 12 Real Estate Option Income ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/rnty/',
                'notes' => 'Target 12 ETF',
            ],
            [
                'security_id' => 129,
                'run_day' => 3,
                'run_hour' => 8,
                'security_name' => 'Global X Russell 2000 Covered Call ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.60,
                'website_url' => 'https://www.globalxetfs.com/funds/ryld/',
                'notes' => null,
            ],
            [
                'security_id' => 130,
                'run_day' => 4,
                'run_hour' => 9,
                'security_name' => 'Global X Russell 2000 Covered Call & Growth ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.60,
                'website_url' => 'https://www.globalxetfs.com/funds/rylg/',
                'notes' => null,
            ],
            [
                'security_id' => 131,
                'run_day' => 5,
                'run_hour' => 10,
                'security_name' => 'Global X MSCI SuperDividend Emerging Markets ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 10,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.58,
                'website_url' => 'https://www.globalxetfs.com/funds/sdem/',
                'notes' => 'Emerging markets dividend ETF',
            ],
            [
                'security_id' => 132,
                'run_day' => 6,
                'run_hour' => 11,
                'security_name' => 'Global X SuperDividend ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 10,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.58,
                'website_url' => 'https://www.globalxetfs.com/funds/sdiv/',
                'notes' => 'Global high dividend ETF',
            ],
            [
                'security_id' => 133,
                'run_day' => 7,
                'run_hour' => 12,
                'security_name' => 'YieldMax S&P 500 0DTE Covered Call Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/sdty/',
                'notes' => '0DTE strategy ETF',
            ],
            [
                'security_id' => 134,
                'run_day' => 1,
                'run_hour' => 13,
                'security_name' => 'Nicholas Silver Income ETF',
                'etf_issuer_id' => 11,
                'etf_strategy_type_id' => 25,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.95,
                'website_url' => 'https://nicholasx.com/slvx/',
                'notes' => 'Silver income ETF',
            ],
            [
                'security_id' => 135,
                'run_day' => 2,
                'run_hour' => 14,
                'security_name' => 'YieldMax SMCI Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/smcy/',
                'notes' => null,
            ],
            [
                'security_id' => 136,
                'run_day' => 3,
                'run_hour' => 15,
                'security_name' => 'YieldMax SNOW Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/snoy/',
                'notes' => null,
            ],
            [
                'security_id' => 137,
                'run_day' => 4,
                'run_hour' => 16,
                'security_name' => 'YieldMax SOXL Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/soxy/',
                'notes' => null,
            ],
            [
                'security_id' => 138,
                'run_day' => 5,
                'run_hour' => 17,
                'security_name' => 'NEOS S&P 500 Hedged Equity Income ETF',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 19,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.58,
                'website_url' => 'https://neosfunds.com/spyh/',
                'notes' => 'Hedged equity ETF',
            ],
            [
                'security_id' => 139,
                'run_day' => 6,
                'run_hour' => 18,
                'security_name' => 'NEOS S&P 500 High Income ETF',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.68,
                'website_url' => 'https://neosfunds.com/spyi/',
                'notes' => null,
            ],
            [
                'security_id' => 140,
                'run_day' => 7,
                'run_hour' => 19,
                'security_name' => 'Defiance S&P 500 Target Income ETF',
                'etf_issuer_id' => 6,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.94,
                'website_url' => 'https://www.defianceetfs.com/spyt/',
                'notes' => 'Target income ETF',
            ],
            [
                'security_id' => 141,
                'run_day' => 1,
                'run_hour' => 20,
                'security_name' => 'Global X SuperDividend REIT ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 10,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.58,
                'website_url' => 'https://www.globalxetfs.com/funds/sret/',
                'notes' => 'REIT dividend ETF',
            ],
            [
                'security_id' => 142,
                'run_day' => 2,
                'run_hour' => 21,
                'security_name' => 'TappAlpha Innovation 100 Growth & Daily Income ETF',
                'etf_issuer_id' => 12,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.77,
                'website_url' => 'https://www.tappalphafunds.com/etfs/tdaq',
                'notes' => 'NASDAQ-100 daily covered call strategy ETF',
            ],
            [
                'security_id' => 143,
                'run_day' => 3,
                'run_hour' => 22,
                'security_name' => 'TDAQ Lift ETF',
                'etf_issuer_id' => 12,
                'etf_strategy_type_id' => 18,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.98,
                'website_url' => 'https://www.tappalphafunds.com/etfs/tdax',
                'notes' => '30% leveraged TDAQ strategy ETF',
            ],
            [
                'security_id' => 144,
                'run_day' => 4,
                'run_hour' => 23,
                'security_name' => 'YieldMax Test ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/test/',
                'notes' => 'Testing or placeholder ETF',
            ],
            [
                'security_id' => 145,
                'run_day' => 5,
                'run_hour' => 0,
                'security_name' => 'NEOS Enhanced Income 20+ Year Treasury Bond ETF',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 9,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.58,
                'website_url' => 'https://neosfunds.com/tlti/',
                'notes' => 'Treasury bond income ETF',
            ],
            [
                'security_id' => 146,
                'run_day' => 6,
                'run_hour' => 1,
                'security_name' => 'Roundhill Top 10 WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/topw/',
                'notes' => 'Portfolio strategy ETF',
            ],
            [
                'security_id' => 147,
                'run_day' => 7,
                'run_hour' => 2,
                'security_name' => 'Roundhill T-Bill & Option Income ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.49,
                'website_url' => 'https://www.roundhillinvestments.com/etf/tpay/',
                'notes' => 'Treasury income strategy ETF',
            ],
            [
                'security_id' => 148,
                'run_day' => 1,
                'run_hour' => 3,
                'security_name' => 'REX TSLA Weekly Income ETF',
                'etf_issuer_id' => 3,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.rexshares.com/tsii/',
                'notes' => null,
            ],
            [
                'security_id' => 149,
                'run_day' => 2,
                'run_hour' => 4,
                'security_name' => 'Kurv Tesla Covered Call ETF',
                'etf_issuer_id' => 10,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.kurvinvest.com/etf/tslp',
                'notes' => null,
            ],
            [
                'security_id' => 150,
                'run_day' => 3,
                'run_hour' => 5,
                'security_name' => 'Roundhill TSLA WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/tslw/',
                'notes' => null,
            ],
            [
                'security_id' => 151,
                'run_day' => 4,
                'run_hour' => 6,
                'security_name' => 'YieldMax TSLA Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/tsly/',
                'notes' => null,
            ],
            [
                'security_id' => 152,
                'run_day' => 5,
                'run_hour' => 7,
                'security_name' => 'YieldMax TSM Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/tsmy/',
                'notes' => null,
            ],
            [
                'security_id' => 153,
                'run_day' => 6,
                'run_hour' => 8,
                'security_name' => 'TappAlpha S&P 500 Growth & Daily Income ETF',
                'etf_issuer_id' => 12,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.77,
                'website_url' => 'https://www.tappalphafunds.com/etfs/tspy',
                'notes' => 'Daily covered call income strategy ETF',
            ],
            [
                'security_id' => 154,
                'run_day' => 7,
                'run_hour' => 9,
                'security_name' => 'Roundhill TSM WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/tsyw/',
                'notes' => null,
            ],
            [
                'security_id' => 155,
                'run_day' => 1,
                'run_hour' => 10,
                'security_name' => 'TSPY Lift ETF',
                'etf_issuer_id' => 12,
                'etf_strategy_type_id' => 18,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.98,
                'website_url' => 'https://www.tappalphafunds.com/etfs/tsyx',
                'notes' => '30% leveraged TSPY strategy ETF',
            ],
            [
                'security_id' => 156,
                'run_day' => 2,
                'run_hour' => 11,
                'security_name' => 'Roundhill UBER WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/ubew/',
                'notes' => null,
            ],
            [
                'security_id' => 157,
                'run_day' => 3,
                'run_hour' => 12,
                'security_name' => 'REX Ultra Income ETF',
                'etf_issuer_id' => 3,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.85,
                'website_url' => 'https://www.rexshares.com/ulti/',
                'notes' => 'Diversified income strategy ETF',
            ],
            [
                'security_id' => 158,
                'run_day' => 4,
                'run_hour' => 13,
                'security_name' => 'YieldMax Ultra Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.24,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/ulty/',
                'notes' => 'Multi-strategy portfolio ETF',
            ],
            [
                'security_id' => 159,
                'run_day' => 5,
                'run_hour' => 14,
                'security_name' => 'Roundhill UNH WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.roundhillinvestments.com/etf/unhw/',
                'notes' => null,
            ],
            [
                'security_id' => 160,
                'run_day' => 6,
                'run_hour' => 15,
                'security_name' => 'Defiance Oil Enhanced Option Income ETF',
                'etf_issuer_id' => 6,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 1.29,
                'website_url' => 'https://www.defianceetfs.com/usoy/',
                'notes' => 'Oil income ETF',
            ],
            [
                'security_id' => 161,
                'run_day' => 7,
                'run_hour' => 16,
                'security_name' => 'Defiance S&P 500 Enhanced Option Income ETF',
                'etf_issuer_id' => 6,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.defianceetfs.com/wdte/',
                'notes' => '0DTE enhanced income ETF',
            ],
            [
                'security_id' => 162,
                'run_day' => 1,
                'run_hour' => 17,
                'security_name' => 'Roundhill WeeklyPay ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.75,
                'website_url' => 'https://www.roundhillinvestments.com/etf/week/',
                'notes' => 'Portfolio strategy ETF',
            ],
            [
                'security_id' => 163,
                'run_day' => 2,
                'run_hour' => 18,
                'security_name' => 'Nicholas Defense & Aerospace Income ETF',
                'etf_issuer_id' => 11,
                'etf_strategy_type_id' => 26,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 1.05,
                'website_url' => 'https://nicholasx.com/wepn/',
                'notes' => 'Defense sector ETF',
            ],
            [
                'security_id' => 164,
                'run_day' => 3,
                'run_hour' => 19,
                'security_name' => 'REX Walmart Weekly Income ETF',
                'etf_issuer_id' => 3,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://www.rexshares.com/wmti/',
                'notes' => null,
            ],
            [
                'security_id' => 165,
                'run_day' => 4,
                'run_hour' => 20,
                'security_name' => 'YieldMax MSTR Short Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.14,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/wntr/',
                'notes' => 'Short strategy ETF',
            ],
            [
                'security_id' => 166,
                'run_day' => 5,
                'run_hour' => 21,
                'security_name' => 'NEOS Bitcoin High Income ETF',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.98,
                'website_url' => 'https://neosfunds.com/xbci/',
                'notes' => 'Bitcoin income ETF',
            ],
            [
                'security_id' => 167,
                'run_day' => 6,
                'run_hour' => 22,
                'security_name' => 'Global X S&P 500 Collar 95-110 ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 17,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.60,
                'website_url' => 'https://www.globalxetfs.com/funds/xclr/',
                'notes' => 'Collar strategy ETF',
            ],
            [
                'security_id' => 168,
                'run_day' => 7,
                'run_hour' => 23,
                'security_name' => 'Roundhill S&P 500 0DTE Covered Call Strategy ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.95,
                'website_url' => 'https://www.roundhillinvestments.com/etf/xdte/',
                'notes' => '0DTE strategy ETF',
            ],
            [
                'security_id' => 169,
                'run_day' => 1,
                'run_hour' => 0,
                'security_name' => 'YieldMax XOM Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/xomo/',
                'notes' => null,
            ],
            [
                'security_id' => 170,
                'run_day' => 2,
                'run_hour' => 1,
                'security_name' => 'Roundhill X-Pay Income ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.59,
                'website_url' => 'https://www.roundhillinvestments.com/etf/xpay/',
                'notes' => 'Income strategy ETF',
            ],
            [
                'security_id' => 171,
                'run_day' => 3,
                'run_hour' => 2,
                'security_name' => 'NEOS Nasdaq 100 High Income ETF - Tax Efficient',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.68,
                'website_url' => 'https://neosfunds.com/xqqi/',
                'notes' => 'Tax-efficient income ETF',
            ],
            [
                'security_id' => 172,
                'run_day' => 4,
                'run_hour' => 3,
                'security_name' => 'NEOS S&P 500 High Income ETF - Tax Efficient',
                'etf_issuer_id' => 9,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.68,
                'website_url' => 'https://neosfunds.com/xspi/',
                'notes' => 'Tax-efficient income ETF',
            ],
            [
                'security_id' => 173,
                'run_day' => 5,
                'run_hour' => 4,
                'security_name' => 'Global X S&P 500 Covered Call ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.60,
                'website_url' => 'https://www.globalxetfs.com/funds/xyld/',
                'notes' => null,
            ],
            [
                'security_id' => 174,
                'run_day' => 6,
                'run_hour' => 5,
                'security_name' => 'Global X S&P 500 Covered Call & Growth ETF',
                'etf_issuer_id' => 5,
                'etf_strategy_type_id' => 1,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.60,
                'website_url' => 'https://www.globalxetfs.com/funds/xylg/',
                'notes' => null,
            ],
            [
                'security_id' => 175,
                'run_day' => 7,
                'run_hour' => 6,
                'security_name' => 'YieldMax XYZ Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/xyzy/',
                'notes' => null,
            ],
            [
                'security_id' => 176,
                'run_day' => 1,
                'run_hour' => 7,
                'security_name' => 'YieldMax Bitcoin Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/ybit/',
                'notes' => 'Bitcoin-related strategy ETF',
            ],
            [
                'security_id' => 177,
                'run_day' => 2,
                'run_hour' => 8,
                'security_name' => 'Defiance Bitcoin Enhanced Option Income ETF',
                'etf_issuer_id' => 6,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 1.29,
                'website_url' => 'https://www.defianceetfs.com/ybmn/',
                'notes' => 'Bitcoin income ETF',
            ],
            [
                'security_id' => 178,
                'run_day' => 3,
                'run_hour' => 9,
                'security_name' => 'Roundhill Bitcoin Covered Call Strategy ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.95,
                'website_url' => 'https://www.roundhillinvestments.com/etf/ybtc/',
                'notes' => 'Bitcoin strategy ETF',
            ],
            [
                'security_id' => 179,
                'run_day' => 4,
                'run_hour' => 10,
                'security_name' => 'Roundhill Ether Covered Call Strategy ETF',
                'etf_issuer_id' => 2,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 4,
                'expense_ratio' => 0.95,
                'website_url' => 'https://www.roundhillinvestments.com/etf/yeth/',
                'notes' => 'Ethereum strategy ETF',
            ],
            [
                'security_id' => 180,
                'run_day' => 5,
                'run_hour' => 11,
                'security_name' => 'YieldMax Magnificent 7 Fund of Option Income ETFs',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.28,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/ymag/',
                'notes' => 'Fund of funds ETF',
            ],
            [
                'security_id' => 181,
                'run_day' => 6,
                'run_hour' => 12,
                'security_name' => 'YieldMax Universe Fund of Option Income ETFs',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 1.28,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/ymax/',
                'notes' => 'Fund of funds ETF',
            ],
            [
                'security_id' => 182,
                'run_day' => 7,
                'run_hour' => 13,
                'security_name' => 'YieldMax QQQ Option Income Strategy ETF',
                'etf_issuer_id' => 1,
                'etf_strategy_type_id' => 6,
                'distribution_frequency_id' => 2,
                'expense_ratio' => 0.99,
                'website_url' => 'https://yieldmaxetfs.com/our-etfs/yqqq/',
                'notes' => null,
            ],
        ];

        $details = array_map(

            function ($detail) use ($now) {

                $detail['created_at'] =
                    $now;

                $detail['updated_at'] =
                    $now;

                return $detail;
            },

            $details

        );

        SecurityDetail::insert(
            $details
        );
    }
}
